### ISSUE TITLE
All colours transparent?

### ISSUE THREAD

**Issue by mppc2001** [rosudrag/se-paintjob#2]
After many attempts all colours still transparent, ships turn black. Is this still being worked on?

**Comment by rosudrag** [comment]
I'm having a break from the game. Feel free to fork and change as you wish :)
I do have some plan for this when I get back. I wanted to mimic the paintgun mod UI for creating the color palette.

**Comment by rosudrag** [comment]
Changed the way the plugin works so that it uses the colors from the game palette.
