### ISSUE TITLE
Paintjob is pulling colors not in palette

### ISSUE THREAD

**Issue by mcbobbo** [rosudrag/se-paintjob#3]
Using this color set:

![image](https://github.com/rosudrag/se-paintjob/assets/8608877/53a43a80-8748-4ed1-b949-1d34fb5e474c)

```
  <ColorSet>
    <Name>gachd-darkmono</Name>
    <Colors>
      <Color b="19" g="23" r="32" />
      <Color b="27" g="32" r="44" />
      <Color b="34" g="41" r="56" />
      <Color b="41" g="50" r="68" />
      <Color b="49" g="59" r="80" />
      <Color b="56" g="68" r="92" />
      <Color b="63" g="77" r="104" />
      <Color b="63" g="77" r="104" />
      <Color b="56" g="68" r="92" />
      <Color b="49" g="59" r="80" />
      <Color b="41" g="50" r="68" />
      <Color b="34" g="41" r="56" />
      <Color b="27" g="32" r="44" />
      <Color b="19" g="23" r="32" />
    </Colors>
  </ColorSet>
```

I am somehow getting orange and red colors.  
![image](https://github.com/rosudrag/se-paintjob/assets/8608877/d9cf9a12-8ed6-4dd6-983d-8f346105400e)
![image](https://github.com/rosudrag/se-paintjob/assets/8608877/93c8a406-e254-4821-8825-946cbf13c710)

When I 'pick' the color it comes over as correct.  But it shows as something weird.

Replacing them with the Paintgun mod is a workaround.

**Comment by rosudrag** [comment]
Updated. Should be okay once plugin hub dudes accept the pr.
